[tool.poetry]
name = "hikari"
version = "0.3.0"
description = "A high-level tool for manipulating crystallographic files"
authors = ["Daniel TchoÅ„"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9"
numpy = ">=1.25"
pandas = ">=1.0.1,!=1.5.0"
scipy = ">=1.5.1"
uncertainties = ">=3"
matplotlib = ">= 3.0.0,!=3.3.*"
seaborn = ">=0.11.0"

[tool.poetry.group.dev.dependencies]
poetry = {version = ">=1.8.0", python = "^3.9"}
flake8 = ">=7"
pytest = ">=8"
pytest-cov = ">=5"
sphinx = ">=7.2"
myst-nb = ">=1.1.2"
sphinx-autoapi = ">=3"
sphinx-rtd-theme = ">=3"
jupyter = ">=1.1"
python-semantic-release = {version = "^9.11.1", python = "^3.8"}
docutils = "!=0.21.post1"

[tool.semantic_release]
version_toml = ["pyproject.toml:tool.poetry.version", ]  # version location
branch = "master"                                        # branch to make releases of
changelog_file = "CHANGELOG.md"                          # changelog file
build_command = "pip install poetry && poetry build"     # build dists
commit_parser = "emoji"                                  # default EmojiCommitParser
major_on_zero = false                                    # change to "true" only if you are sure you want version 1
commit_message = ":bookmark: v{version}\n\nAutomatically generated by python-semantic-release"

[tool.semantic_release.branches]
master = { publish = true }        # Stable release branch (master)
development = { publish = false }  # Used for version checking only

[tool.semantic_release.commit_parser_options]
major_tags = [                          # CAUSE MAJOR VERSION BUMP 0.1.0 -> 1.0.0
    ":boom:",                           # ðŸ’¥ Introduce breaking changes.
]
minor_tags = [                          # CAUSE MINOR VERSION BUMP 0.1.0 -> 0.2.0
    ":sparkles:",                       # âœ¨ Introduce new features.
]
patch_tags = [                          # CAUSE PATCH VERSION BUMP 0.1.0 -> 0.1.1
    ":adhesive_bandage:",               # ðŸ©¹ Simple fix for a non-critical issue.
    ":ambulance:",                      # ðŸš‘ï¸ Critical hotfix.
    ":alien:",                          # ðŸ‘½ï¸ Update code due to external API changes.
    ":alembic:",                        # âš—ï¸ Perform experiments.
    ":arrow_down:",                     # â¬‡ï¸ Downgrade dependencies.
    ":arrow_up:",                       # â¬†ï¸ Upgrade dependencies.
    ":bento:",                          # ðŸ± Add or update assets.
    ":bug:",                            # ðŸ› Fix a bug.
    ":card_file_box:",                  # ðŸ—ƒï¸ Perform database related changes.
    ":chart_with_upwards_trend:",       # ðŸ“ˆ Add or update analytics or track code.
    ":children_crossing:",              # ðŸš¸ Improve user experience / usability.
    ":dizzy:",                          # ðŸ’« Add or update animations and transitions.
    ":egg:",                            # ðŸ¥š Add or update an easter egg.
    ":globe_with_meridians:",           # ðŸŒ Internationalization and localization.
    ":goal_net:",                       # ðŸ¥… Catch errors.
    ":heavy_plus_sign:",                # âž• Add a dependency.
    ":heavy_minus_sign:",               # âž– Remove a dependency.
    ":iphone:",                         # ðŸ“± Work on responsive design.
    ":lipstick:",                       # ðŸ’„ Add or update the UI and style files.
    ":label:",                          # ðŸ·ï¸ Add or update types.
    ":lock:",                           # ðŸ”’ï¸ Fix security or privacy issues.
    ":mag:",                            # ðŸ”ï¸ Improve SEO.
    ":necktie:",                        # ðŸ‘” Add or update business logic.
    ":package:",                        # ðŸ“¦ï¸ Add or update compiled files or packages.
    ":passport_control:",               # ðŸ›‚ Work on code related to authorization, roles and permissions.
    ":pencil2:",                        # âœï¸ Fix typos.
    ":push_pin:",                       # ðŸ“Œï¸ Pin dependencies to specific versions.
    ":rewind:",                         # âªï¸ Revert changes.
    ":speech_balloon:",                 # ðŸ’¬ Add or update text and literals.
    ":triangular_flag_on_post:",        # ðŸš© Add, update, or remove feature flags.
    ":wastebasket:",                    # ðŸ—‘ï¸ Deprecate code that needs to be cleaned up.
    ":wheelchair:",                     # â™¿ï¸ Improve accessability.
    ":wrench:",                         # ðŸ”§ Add or update configuration files.
    ":zap:",                            # âš¡ï¸ Improve performance.
]
other_tags = [                          # UNSUPPORTED - DO NOT CAUSE VERSION BUMP
    ":art:",                            # ðŸŽ¨ Improve structure / format of the code.
    ":beers:",                          # ðŸ» Write code drunkenly.
    ":bookmark:",                       # ðŸ”– Release / Version tags.
    ":bricks:",                         # ðŸ§± Infrastructure related changes.
    ":bulb:",                           # ðŸ’¡ Add or update comments in source code.
    ":building_construction:",          # ðŸ—ï¸ Make architectural changes.
    ":busts_in_silhouette:",            # ðŸ‘¥ Add or update contributor(s).
    ":camera_flash:",                   # ðŸ“¸ Add or update snapshots.
    ":closed_lock_with_key:",           # ðŸ” Add or update secrets.
    ":clown_face:",                     # ðŸ¤¡ Mock things.
    ":coffin:",                         # âš°ï¸ Remove dead code.
    ":construction:",                   # ðŸš§ Work in progress.
    ":construction_worker:",            # ðŸ‘· Add or update CI build system.
    ":fire:",                           # ðŸ”¥ Remove code or files.
    ":green_heart:",                    # ðŸ’š Fix CI Build.
    ":hammer:",                         # ðŸ”¨ Add or update development scripts.
    ":loud_sounds:",                    # ðŸ”Š Add or update logs.
    ":memo:",                           # ðŸ“ Add or update documentation.
    ":money_with_wings:",               # ðŸ’¸ Add sponsorships or money related infrastructure.
    ":monocle_face:",                   # ðŸ§ Data exploration/inspection.
    ":mute:",                           # ðŸ”‡ Remove logs.
    ":page_facing_up:",                 # ðŸ“„ Add or update license.
    ":poop:",                           # ðŸ’© Write bad code that needs to be improved.
    ":recycle:",                        # â™»ï¸ Refactor code.
    ":rocket:",                         # ðŸš€ Deploy stuff.
    ":rotating_light:",                 # ðŸš¨ Fix compiler / linter warnings.
    ":safety_vest:",                    # ðŸ¦º Add or update code related to validation.
    ":see_no_evil:",                    # ðŸ™ˆ Add or update a .gitignore file.
    ":seedling:",                       # ðŸŒ± Add or update seed files.
    ":stethoscope:",                    # ðŸ©º Add or update healthcheck.
    ":tada:",                           # ðŸŽ‰ Begin a project.
    ":technologist:",                   # ðŸ§‘â€ðŸ’» Improve developer experience.
    ":test_tube:",                      # ðŸ§ª Add a failing test.
    ":thread:",                         # ðŸ§µ Add or update code related to multithreading or concurrency.
    ":truck:",                          # ðŸšš Move or rename resources (e.g.: files, paths, routes).
    ":twisted_rightwards_arrows:",      # ðŸ”€ Merge branches.
    ":white_check_mark:",               # âœ… Add, update, or pass tests.
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
